language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: bSTFgrE4EEhRWha36hUeU/o/Jh5NXNeQ4WcC+rT7Q2qgWQ5MxIqUMBu5dkCClQS9yuXwa4SzPT12wkd2iafPqICzb4Iy/WXR+ajxnCERb/WLkwbqO2g+ormLLPSkV1182hWeONDWX2RbCrfZ7Ah46EKj4Awt94Ym50dDW+ZcQsPQG/Y2Hm6Cf5hUFPYtbQPhLA8u3N6PO31PXwi4O+khnFwokVJL+08ii7v24FktHfv81PQGLmZbp8ncHl8JOIPFGMf8iLpNN5MEOmlNXqlviuea8Q5PilDKkTMYZ18SjWDf8oEpNX41CLlGZHu5Gyg4OmYhC/m8+uW4DS7zHuO7Ww2cTpjXrjK3IIcPRTJJm37kD/GBgk0Lzaznkyeor4I4jo8mKaSTyVbQQ00O4NjIIF8klqxyaUKt1yeXoVlUMAdZHTQoo3guLOW17OuCliSvCPrvDBVdKJNgn2i0wtM3EEvopCeAzIgcj5G+09jweN9pMWYQArfP6sC6bh1+2zyEGXdI0wU5yyAPI1k9oBv+ayjV4fUWFqVGiI0O8Yask0xxVQzcIBkhHLmU9ijUw7zTXSLqjjTLadsLvuByz6uULFoIZUMFMbC6tT0tjWCTT5ciJiG2MbkZ8m94Cvrtb2zVo41TbVHqERvBdGaKLZ26dYIEG87E1a3UhjK9I9ZR6/M=
  app: munch-minder
  on:
    repo: chang-steven/munch-minder
